# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Lane for distributing app to testers"
  lane :distribute do
      gradle(task: 'clean')
      gradle(
        task: 'assemble',
        build_type: 'Qa'
        )
     # increment_app_version_code()
      show_version()
     # increment_app_version_code_name()
      app_distribution()
   end

   desc "Lane for distributing app using Firebase App Distributions"
   private_lane :app_distribution do |options|
      firebase_app_distribution(
          service_credentials_file: "iw_assignment_play_config.json",
          app: ENV["APP"],
          release_notes: "Note: QA test",
          groups: "Qa",
          firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
        )
   end

   desc "Lane for incrementing version code of apk"
   # This works perfect
   private_lane :increment_app_version_code do |options|
       increment_version_code(
               gradle_file_path: "app/build.gradle"
         )
   end

   desc "Lane to show versions"
   private_lane :show_version do |options|
      version = get_version_name(app_project_dir: '**/app')
      UI.message("Default: " + version)
      version_code = get_version_code(app_project_dir: '**/app')
      UI.message("Default: " + version_code)
   end

   desc "Lane for incrementing versionCode & versionName of apk depends on build"
   private_lane :increment_app_version_code_name do |options|
      increment_version_code(app_project_dir: '**/app', flavor: "qa")
      increment_version_name(
          app_project_dir: '**/app',
          bump_type: 'patch',
          flavor: 'qa'
        )
   end
end
