# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Lane for distributing app using Firebase App Distributions"
    lane :distribute do
        gradle(task: "clean assembleQa")
        fastlane_firebase_app_distribution(
            service_credentials_file: "iw_assignment_play_config.json",
            app: "1:197141527930:android:2e82c192a530471c34aac3",
           # release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            release_note: "Note: QA test"
            groups: "Qa",
            firebase_cli_token: "1//0gd29wq-7vyTcCgYIARAAGBASNwF-L9IrAVnuv-G34MEErW92aBky9_J3-G5lK9KqkTw0h9_-K0Kx2vZfaV4-w73fyj_ePMpgTTs"
        )
    end
end
